version: '3'
services:
    manager-nginx:
        build:
            context: ./manager/docker/development
            dockerfile: nginx.docker
        restart: always
        volumes:
            - ./manager:/app
        depends_on:
            - manager-php-fpm
        ports:
            - "8080:80"
    manager-php-fpm:
        build:
            context: ./manager/docker/development
            dockerfile: php-fpm.docker
        volumes:
            - ./manager:/app
        depends_on:
            - manager-mysql
        environment:
            PHP_IDE_CONFIG: serverName=Symfony
    manager-php-cli:
        build:
            context: ./manager/docker/development
            dockerfile: php-cli.docker
        volumes:
            - ./manager:/app
            - composer:/root/.composer/cache
        depends_on:
            - manager-mysql
    manager-mysql:
        image: mysql:5.7
        restart: always
        volumes:
           # - ./docker/storage/mysql:/var/lib/mysql
            - manager-mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=1111"
            - "MYSQL_USER=dbuser"
            - "MYSQL_PASSWORD=2222"
            - "MYSQL_DATABASE=manager"
        ports:
            - "33061:3306"
    manager-phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - manager-mysql:db
        ports:
            - 8081:80
        environment:
            MYSQL_ROOT_PASSWORD: 1111
        depends_on:
            - manager-mysql
volumes:
    manager-mysql:
    composer: